### ISSUE TITLE
ib_send_bw (perftest)  get ERROR: Couldn't allocate MR failed to create mr

### ISSUE THREAD

**Issue by zhengjingwei** [zrlio/softiwarp#23]
when I use `rping ` ,it works. But when I use perftest ,such as `ib_send_bw ` or `ib_send_lat` , then returns ERROR like that:
 ---------------------------------------------------------------------------------------
Couldn't allocate MR
failed to create mr
Failed to create MR
Segmentation fault (core dumped)

**Comment by zhengjingwei** [comment]
```

root@ubuntu:/home/zjw/sw/softiwarp# ib_send_bw  192.168.15.147 -a
---------------------------------------------------------------------------------------
                    Send BW Test
 Dual-port       : OFF		Device         : siw_ens33
 Number of qps   : 1		Transport type : IW
 Connection type : RC		Using SRQ      : OFF
 TX depth        : 128
 CQ Moderation   : 100
 Mtu             : 1024[B]
 Link type       : Ethernet
 Gid index       : 0
 Max inline data : 0[B]
 rdma_cm QPs	 : OFF
 Data ex. method : Ethernet
---------------------------------------------------------------------------------------
Couldn't allocate MR
failed to create mr
Failed to create MR
Segmentation fault (core dumped)


```
```
root@ubuntu:/home/zjw/sw/softiwarp# rping -c -a 192.168.15.147 -v
ping data: rdma-ping-0: ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqr
ping data: rdma-ping-1: BCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrs
ping data: rdma-ping-2: CDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrst
ping data: rdma-ping-3: DEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstu
ping data: rdma-ping-4: EFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuv
ping data: rdma-ping-5: FGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvw
ping data: rdma-ping-6: GHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwx
ping data: rdma-ping-7: HIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxy
ping data: rdma-ping-8: IJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz
ping data: rdma-ping-9: JKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyzA
ping data: rdma-ping-10: KLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyzA
```

**Comment by BernardMetzler** [comment]
Hi Jingwei,

likely, your system does not allow to register larger chunks of 
application buffers. please try enabling larger registrations by
editing /etc/security/limits.conf and starting a new shell.

adding

*            soft    memlock         unlimited
*            hard    memlock         unlimited

to that file gives unlimited memory pinning capabilities to
all uses. change '*' to a user name as appropriate.

Also, add needed flag to ib_send_bw & friends to
switch it to RDMA_CM connection management ('-R' flag, 
see 'ib_read_bw --h')

iwarp RDMA providers use the generic RDMA_CM connection
manager.

For reasonable performance numbers, run your tests on the
same NUMA node as the Ethernet card you are using (numactl).
Maybe also limit the siw TX threads to that NUMA node
(kernel module parameter 'iface_list', to be set
during module loading). And set your CPU to a good C-state,
it's all software RDMA ;)

Thanks
Bernard.

-----Jingwei Zheng <notifications@github.com> wrote: -----
To: zrlio/softiwarp <softiwarp@noreply.github.com>

**Comment by zhengjingwei** [comment]
Hi Bernard,
  Thanks!  The solution works.

**Comment by xuchenhui-5** [comment]
well done！ thanks！
